// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_to_server_messages.proto

package greyvarproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MoveRequest struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3412f9c567d3c300, []int{0}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MoveRequest) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveRequest) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type ConnectionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3412f9c567d3c300, []int{1}
}

func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (m *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(m, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

type NewPlayer struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewPlayer) Reset()         { *m = NewPlayer{} }
func (m *NewPlayer) String() string { return proto.CompactTextString(m) }
func (*NewPlayer) ProtoMessage()    {}
func (*NewPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_3412f9c567d3c300, []int{2}
}

func (m *NewPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPlayer.Unmarshal(m, b)
}
func (m *NewPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPlayer.Marshal(b, m, deterministic)
}
func (m *NewPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPlayer.Merge(m, src)
}
func (m *NewPlayer) XXX_Size() int {
	return xxx_messageInfo_NewPlayer.Size(m)
}
func (m *NewPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_NewPlayer proto.InternalMessageInfo

func (m *NewPlayer) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*MoveRequest)(nil), "greyvarproto.MoveRequest")
	proto.RegisterType((*ConnectionRequest)(nil), "greyvarproto.ConnectionRequest")
	proto.RegisterType((*NewPlayer)(nil), "greyvarproto.NewPlayer")
}

func init() { proto.RegisterFile("client_to_server_messages.proto", fileDescriptor_3412f9c567d3c300) }

var fileDescriptor_3412f9c567d3c300 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xce, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0xc6, 0x71, 0xb6, 0x28, 0x72, 0xf3, 0x92, 0x5d, 0xa4, 0x4b, 0xe1, 0xa5, 0x4e, 0x5d, 0x7a,
	0x84, 0xe8, 0xd0, 0xa1, 0x08, 0x5f, 0x40, 0x36, 0xfb, 0x10, 0x41, 0x77, 0x6d, 0x66, 0x35, 0xf7,
	0xed, 0xc3, 0x2d, 0x3c, 0xfe, 0x06, 0xe6, 0xcf, 0x27, 0xb7, 0x79, 0x55, 0x42, 0xdb, 0xcc, 0x9a,
	0x8c, 0x41, 0x1d, 0x28, 0xab, 0xc1, 0xac, 0x0a, 0xf0, 0xb1, 0x21, 0x63, 0x4d, 0x14, 0x16, 0x04,
	0xd7, 0x29, 0xf2, 0x4a, 0x2e, 0x72, 0x79, 0x33, 0x1d, 0x52, 0xbc, 0x5b, 0xb0, 0x8d, 0x36, 0x72,
	0xd1, 0x54, 0xca, 0x81, 0xae, 0xaf, 0x58, 0xec, 0xc4, 0x61, 0x96, 0x8e, 0x8e, 0x42, 0x29, 0xfa,
	0x78, 0xe2, 0x8f, 0xa2, 0x1f, 0xe4, 0xe2, 0xe9, 0x4f, 0x2e, 0x59, 0xcb, 0xd5, 0xd9, 0x68, 0x8d,
	0xdc, 0x96, 0x46, 0xff, 0x63, 0xc9, 0x5e, 0x06, 0x77, 0x7c, 0x1e, 0xfe, 0x7f, 0x28, 0xb7, 0x0c,
	0xd2, 0xaa, 0x86, 0x2f, 0x07, 0xe9, 0xe8, 0xe7, 0xdc, 0x6f, 0x39, 0x7d, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x5e, 0xa3, 0xdf, 0x89, 0xbc, 0x00, 0x00, 0x00,
}
