// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_to_client_messages.proto

package greyvarproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerFrameResponse struct {
	PlayerFrames         []*PlayerFrame `protobuf:"bytes,1,rep,name=playerFrames,proto3" json:"playerFrames,omitempty"`
	EntityMoved          *EntityMoved   `protobuf:"bytes,2,opt,name=entityMoved,proto3" json:"entityMoved,omitempty"`
	EntitySpawn          *EntitySpawn   `protobuf:"bytes,3,opt,name=entitySpawn,proto3" json:"entitySpawn,omitempty"`
	PlayerJoined         *PlayerJoined  `protobuf:"bytes,4,opt,name=playerJoined,proto3" json:"playerJoined,omitempty"`
	SingleTileChange     *Tile          `protobuf:"bytes,5,opt,name=singleTileChange,proto3" json:"singleTileChange,omitempty"`
	Grid                 *Grid          `protobuf:"bytes,6,opt,name=grid,proto3" json:"grid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServerFrameResponse) Reset()         { *m = ServerFrameResponse{} }
func (m *ServerFrameResponse) String() string { return proto.CompactTextString(m) }
func (*ServerFrameResponse) ProtoMessage()    {}
func (*ServerFrameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{0}
}

func (m *ServerFrameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerFrameResponse.Unmarshal(m, b)
}
func (m *ServerFrameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerFrameResponse.Marshal(b, m, deterministic)
}
func (m *ServerFrameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerFrameResponse.Merge(m, src)
}
func (m *ServerFrameResponse) XXX_Size() int {
	return xxx_messageInfo_ServerFrameResponse.Size(m)
}
func (m *ServerFrameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerFrameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerFrameResponse proto.InternalMessageInfo

func (m *ServerFrameResponse) GetPlayerFrames() []*PlayerFrame {
	if m != nil {
		return m.PlayerFrames
	}
	return nil
}

func (m *ServerFrameResponse) GetEntityMoved() *EntityMoved {
	if m != nil {
		return m.EntityMoved
	}
	return nil
}

func (m *ServerFrameResponse) GetEntitySpawn() *EntitySpawn {
	if m != nil {
		return m.EntitySpawn
	}
	return nil
}

func (m *ServerFrameResponse) GetPlayerJoined() *PlayerJoined {
	if m != nil {
		return m.PlayerJoined
	}
	return nil
}

func (m *ServerFrameResponse) GetSingleTileChange() *Tile {
	if m != nil {
		return m.SingleTileChange
	}
	return nil
}

func (m *ServerFrameResponse) GetGrid() *Grid {
	if m != nil {
		return m.Grid
	}
	return nil
}

type PlayerFrame struct {
	PlayerId             int32         `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	MoveResponse         *MoveResponse `protobuf:"bytes,2,opt,name=moveResponse,proto3" json:"moveResponse,omitempty"`
	PlayerQuit           *PlayerQuit   `protobuf:"bytes,3,opt,name=playerQuit,proto3" json:"playerQuit,omitempty"`
	PlayerYou            *PlayerYou    `protobuf:"bytes,4,opt,name=playerYou,proto3" json:"playerYou,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlayerFrame) Reset()         { *m = PlayerFrame{} }
func (m *PlayerFrame) String() string { return proto.CompactTextString(m) }
func (*PlayerFrame) ProtoMessage()    {}
func (*PlayerFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{1}
}

func (m *PlayerFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerFrame.Unmarshal(m, b)
}
func (m *PlayerFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerFrame.Marshal(b, m, deterministic)
}
func (m *PlayerFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerFrame.Merge(m, src)
}
func (m *PlayerFrame) XXX_Size() int {
	return xxx_messageInfo_PlayerFrame.Size(m)
}
func (m *PlayerFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerFrame proto.InternalMessageInfo

func (m *PlayerFrame) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerFrame) GetMoveResponse() *MoveResponse {
	if m != nil {
		return m.MoveResponse
	}
	return nil
}

func (m *PlayerFrame) GetPlayerQuit() *PlayerQuit {
	if m != nil {
		return m.PlayerQuit
	}
	return nil
}

func (m *PlayerFrame) GetPlayerYou() *PlayerYou {
	if m != nil {
		return m.PlayerYou
	}
	return nil
}

type MoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{2}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

type EntityMoved struct {
	EntityId             int32    `protobuf:"varint,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityMoved) Reset()         { *m = EntityMoved{} }
func (m *EntityMoved) String() string { return proto.CompactTextString(m) }
func (*EntityMoved) ProtoMessage()    {}
func (*EntityMoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{3}
}

func (m *EntityMoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityMoved.Unmarshal(m, b)
}
func (m *EntityMoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityMoved.Marshal(b, m, deterministic)
}
func (m *EntityMoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityMoved.Merge(m, src)
}
func (m *EntityMoved) XXX_Size() int {
	return xxx_messageInfo_EntityMoved.Size(m)
}
func (m *EntityMoved) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityMoved.DiscardUnknown(m)
}

var xxx_messageInfo_EntityMoved proto.InternalMessageInfo

func (m *EntityMoved) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

type EntitySpawn struct {
	EntityId             int32    `protobuf:"varint,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	W                    int32    `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"`
	H                    int32    `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"`
	Texture              string   `protobuf:"bytes,6,opt,name=texture,proto3" json:"texture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntitySpawn) Reset()         { *m = EntitySpawn{} }
func (m *EntitySpawn) String() string { return proto.CompactTextString(m) }
func (*EntitySpawn) ProtoMessage()    {}
func (*EntitySpawn) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{4}
}

func (m *EntitySpawn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntitySpawn.Unmarshal(m, b)
}
func (m *EntitySpawn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntitySpawn.Marshal(b, m, deterministic)
}
func (m *EntitySpawn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntitySpawn.Merge(m, src)
}
func (m *EntitySpawn) XXX_Size() int {
	return xxx_messageInfo_EntitySpawn.Size(m)
}
func (m *EntitySpawn) XXX_DiscardUnknown() {
	xxx_messageInfo_EntitySpawn.DiscardUnknown(m)
}

var xxx_messageInfo_EntitySpawn proto.InternalMessageInfo

func (m *EntitySpawn) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *EntitySpawn) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *EntitySpawn) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *EntitySpawn) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *EntitySpawn) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *EntitySpawn) GetTexture() string {
	if m != nil {
		return m.Texture
	}
	return ""
}

type PlayerQuit struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerQuit) Reset()         { *m = PlayerQuit{} }
func (m *PlayerQuit) String() string { return proto.CompactTextString(m) }
func (*PlayerQuit) ProtoMessage()    {}
func (*PlayerQuit) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{5}
}

func (m *PlayerQuit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerQuit.Unmarshal(m, b)
}
func (m *PlayerQuit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerQuit.Marshal(b, m, deterministic)
}
func (m *PlayerQuit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerQuit.Merge(m, src)
}
func (m *PlayerQuit) XXX_Size() int {
	return xxx_messageInfo_PlayerQuit.Size(m)
}
func (m *PlayerQuit) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerQuit.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerQuit proto.InternalMessageInfo

func (m *PlayerQuit) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type PlayerAlreadyHere struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAlreadyHere) Reset()         { *m = PlayerAlreadyHere{} }
func (m *PlayerAlreadyHere) String() string { return proto.CompactTextString(m) }
func (*PlayerAlreadyHere) ProtoMessage()    {}
func (*PlayerAlreadyHere) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{6}
}

func (m *PlayerAlreadyHere) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAlreadyHere.Unmarshal(m, b)
}
func (m *PlayerAlreadyHere) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAlreadyHere.Marshal(b, m, deterministic)
}
func (m *PlayerAlreadyHere) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAlreadyHere.Merge(m, src)
}
func (m *PlayerAlreadyHere) XXX_Size() int {
	return xxx_messageInfo_PlayerAlreadyHere.Size(m)
}
func (m *PlayerAlreadyHere) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAlreadyHere.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAlreadyHere proto.InternalMessageInfo

func (m *PlayerAlreadyHere) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type PlayerJoined struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerJoined) Reset()         { *m = PlayerJoined{} }
func (m *PlayerJoined) String() string { return proto.CompactTextString(m) }
func (*PlayerJoined) ProtoMessage()    {}
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{7}
}

func (m *PlayerJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerJoined.Unmarshal(m, b)
}
func (m *PlayerJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerJoined.Marshal(b, m, deterministic)
}
func (m *PlayerJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerJoined.Merge(m, src)
}
func (m *PlayerJoined) XXX_Size() int {
	return xxx_messageInfo_PlayerJoined.Size(m)
}
func (m *PlayerJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerJoined.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerJoined proto.InternalMessageInfo

func (m *PlayerJoined) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type PlayerYou struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerYou) Reset()         { *m = PlayerYou{} }
func (m *PlayerYou) String() string { return proto.CompactTextString(m) }
func (*PlayerYou) ProtoMessage()    {}
func (*PlayerYou) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{8}
}

func (m *PlayerYou) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerYou.Unmarshal(m, b)
}
func (m *PlayerYou) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerYou.Marshal(b, m, deterministic)
}
func (m *PlayerYou) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerYou.Merge(m, src)
}
func (m *PlayerYou) XXX_Size() int {
	return xxx_messageInfo_PlayerYou.Size(m)
}
func (m *PlayerYou) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerYou.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerYou proto.InternalMessageInfo

func (m *PlayerYou) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type Tile struct {
	Col                  uint32   `protobuf:"varint,1,opt,name=col,proto3" json:"col,omitempty"`
	Row                  uint32   `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Tex                  string   `protobuf:"bytes,3,opt,name=tex,proto3" json:"tex,omitempty"`
	FlipH                bool     `protobuf:"varint,4,opt,name=flipH,proto3" json:"flipH,omitempty"`
	FlipV                bool     `protobuf:"varint,5,opt,name=flipV,proto3" json:"flipV,omitempty"`
	Rot                  int32    `protobuf:"varint,6,opt,name=rot,proto3" json:"rot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tile) Reset()         { *m = Tile{} }
func (m *Tile) String() string { return proto.CompactTextString(m) }
func (*Tile) ProtoMessage()    {}
func (*Tile) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{9}
}

func (m *Tile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tile.Unmarshal(m, b)
}
func (m *Tile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tile.Marshal(b, m, deterministic)
}
func (m *Tile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tile.Merge(m, src)
}
func (m *Tile) XXX_Size() int {
	return xxx_messageInfo_Tile.Size(m)
}
func (m *Tile) XXX_DiscardUnknown() {
	xxx_messageInfo_Tile.DiscardUnknown(m)
}

var xxx_messageInfo_Tile proto.InternalMessageInfo

func (m *Tile) GetCol() uint32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *Tile) GetRow() uint32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Tile) GetTex() string {
	if m != nil {
		return m.Tex
	}
	return ""
}

func (m *Tile) GetFlipH() bool {
	if m != nil {
		return m.FlipH
	}
	return false
}

func (m *Tile) GetFlipV() bool {
	if m != nil {
		return m.FlipV
	}
	return false
}

func (m *Tile) GetRot() int32 {
	if m != nil {
		return m.Rot
	}
	return 0
}

type Grid struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Tiles                []*Tile  `protobuf:"bytes,2,rep,name=tiles,proto3" json:"tiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Grid) Reset()         { *m = Grid{} }
func (m *Grid) String() string { return proto.CompactTextString(m) }
func (*Grid) ProtoMessage()    {}
func (*Grid) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{10}
}

func (m *Grid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grid.Unmarshal(m, b)
}
func (m *Grid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grid.Marshal(b, m, deterministic)
}
func (m *Grid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grid.Merge(m, src)
}
func (m *Grid) XXX_Size() int {
	return xxx_messageInfo_Grid.Size(m)
}
func (m *Grid) XXX_DiscardUnknown() {
	xxx_messageInfo_Grid.DiscardUnknown(m)
}

var xxx_messageInfo_Grid proto.InternalMessageInfo

func (m *Grid) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Grid) GetTiles() []*Tile {
	if m != nil {
		return m.Tiles
	}
	return nil
}

type ConnectionResponse struct {
	ServerVersion        string               `protobuf:"bytes,1,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	PlayerAlreadyHere    []*PlayerAlreadyHere `protobuf:"bytes,5,rep,name=playerAlreadyHere,proto3" json:"playerAlreadyHere,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConnectionResponse) Reset()         { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()    {}
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{11}
}

func (m *ConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionResponse.Unmarshal(m, b)
}
func (m *ConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionResponse.Marshal(b, m, deterministic)
}
func (m *ConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionResponse.Merge(m, src)
}
func (m *ConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionResponse.Size(m)
}
func (m *ConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionResponse proto.InternalMessageInfo

func (m *ConnectionResponse) GetServerVersion() string {
	if m != nil {
		return m.ServerVersion
	}
	return ""
}

func (m *ConnectionResponse) GetPlayerAlreadyHere() []*PlayerAlreadyHere {
	if m != nil {
		return m.PlayerAlreadyHere
	}
	return nil
}

type NoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoResponse) Reset()         { *m = NoResponse{} }
func (m *NoResponse) String() string { return proto.CompactTextString(m) }
func (*NoResponse) ProtoMessage()    {}
func (*NoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f34367b8a54972c, []int{12}
}

func (m *NoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoResponse.Unmarshal(m, b)
}
func (m *NoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoResponse.Marshal(b, m, deterministic)
}
func (m *NoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoResponse.Merge(m, src)
}
func (m *NoResponse) XXX_Size() int {
	return xxx_messageInfo_NoResponse.Size(m)
}
func (m *NoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ServerFrameResponse)(nil), "greyvarproto.ServerFrameResponse")
	proto.RegisterType((*PlayerFrame)(nil), "greyvarproto.PlayerFrame")
	proto.RegisterType((*MoveResponse)(nil), "greyvarproto.MoveResponse")
	proto.RegisterType((*EntityMoved)(nil), "greyvarproto.EntityMoved")
	proto.RegisterType((*EntitySpawn)(nil), "greyvarproto.EntitySpawn")
	proto.RegisterType((*PlayerQuit)(nil), "greyvarproto.PlayerQuit")
	proto.RegisterType((*PlayerAlreadyHere)(nil), "greyvarproto.PlayerAlreadyHere")
	proto.RegisterType((*PlayerJoined)(nil), "greyvarproto.PlayerJoined")
	proto.RegisterType((*PlayerYou)(nil), "greyvarproto.PlayerYou")
	proto.RegisterType((*Tile)(nil), "greyvarproto.Tile")
	proto.RegisterType((*Grid)(nil), "greyvarproto.Grid")
	proto.RegisterType((*ConnectionResponse)(nil), "greyvarproto.ConnectionResponse")
	proto.RegisterType((*NoResponse)(nil), "greyvarproto.NoResponse")
}

func init() { proto.RegisterFile("server_to_client_messages.proto", fileDescriptor_5f34367b8a54972c) }

var fileDescriptor_5f34367b8a54972c = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xdf, 0x6b, 0x13, 0x41,
	0x10, 0xc7, 0xb9, 0x36, 0x57, 0x9b, 0xc9, 0x55, 0xda, 0x55, 0xf0, 0xec, 0x4b, 0xc3, 0x22, 0x1a,
	0x7d, 0x88, 0xa0, 0x08, 0x82, 0x58, 0x90, 0x62, 0xad, 0x42, 0x44, 0xb7, 0x12, 0xe8, 0x53, 0x38,
	0x73, 0x63, 0xb2, 0x70, 0xd9, 0x3d, 0xf6, 0x36, 0x3f, 0x4e, 0xff, 0x02, 0xff, 0x45, 0xff, 0x10,
	0x9f, 0x65, 0x77, 0xef, 0x72, 0x97, 0xe6, 0xcc, 0xdb, 0x7e, 0x67, 0x3f, 0x33, 0x99, 0xf9, 0xce,
	0xe6, 0xe0, 0x2c, 0x43, 0xb5, 0x40, 0x35, 0xd2, 0x72, 0x34, 0x4e, 0x38, 0x0a, 0x3d, 0x9a, 0x61,
	0x96, 0x45, 0x13, 0xcc, 0xfa, 0xa9, 0x92, 0x5a, 0x92, 0x60, 0xa2, 0x30, 0x5f, 0x44, 0xca, 0x2a,
	0xfa, 0x77, 0x0f, 0xee, 0x5d, 0xdb, 0x8c, 0x4b, 0x15, 0xcd, 0x90, 0x61, 0x96, 0x4a, 0x91, 0x21,
	0x79, 0x0b, 0x41, 0x9a, 0x44, 0x79, 0x11, 0xce, 0x42, 0xaf, 0xbb, 0xdf, 0xeb, 0xbc, 0x78, 0xd8,
	0xaf, 0x27, 0xf7, 0xbf, 0x54, 0x04, 0xdb, 0xc0, 0xc9, 0x1b, 0xe8, 0xa0, 0xd0, 0x5c, 0xe7, 0x03,
	0xb9, 0xc0, 0x38, 0xdc, 0xeb, 0x7a, 0xdb, 0xd9, 0xef, 0x2b, 0x80, 0xd5, 0xe9, 0x2a, 0xf9, 0x3a,
	0x8d, 0x96, 0x22, 0xdc, 0xff, 0x7f, 0xb2, 0x05, 0x58, 0x9d, 0x26, 0xe7, 0x65, 0xe3, 0x9f, 0x24,
	0x17, 0x18, 0x87, 0x2d, 0x9b, 0x7d, 0xda, 0xd4, 0xb8, 0x23, 0xd8, 0x06, 0x4f, 0xce, 0xe1, 0x38,
	0xe3, 0x62, 0x92, 0xe0, 0x37, 0x9e, 0xe0, 0xc5, 0x34, 0x12, 0x13, 0x0c, 0x7d, 0x5b, 0x83, 0x6c,
	0xd6, 0x30, 0xf7, 0x6c, 0x8b, 0x25, 0x8f, 0xa1, 0x35, 0x51, 0x3c, 0x0e, 0x0f, 0x9a, 0x72, 0x3e,
	0x28, 0x1e, 0x33, 0x7b, 0x4f, 0xff, 0x78, 0xd0, 0xa9, 0xf9, 0x47, 0x4e, 0xe1, 0xd0, 0xf5, 0xf1,
	0x31, 0x0e, 0xbd, 0xae, 0xd7, 0xf3, 0xd9, 0x5a, 0x9b, 0x99, 0x66, 0x72, 0xb1, 0x5e, 0x4e, 0x61,
	0xe7, 0xad, 0x99, 0x06, 0x35, 0x82, 0x6d, 0xf0, 0xe4, 0x35, 0x80, 0xab, 0xf5, 0x75, 0xce, 0x75,
	0xe1, 0x67, 0xd8, 0xe4, 0x88, 0xb9, 0x67, 0x35, 0x96, 0xbc, 0x82, 0xb6, 0x53, 0x37, 0x72, 0x5e,
	0x58, 0xf9, 0xa0, 0x29, 0xf1, 0x46, 0xce, 0x59, 0x45, 0xd2, 0xbb, 0x10, 0xd4, 0xdb, 0xa1, 0x4f,
	0xa1, 0x53, 0xdb, 0xb6, 0x99, 0xd5, 0xad, 0xac, 0x9a, 0xb5, 0xd4, 0xf4, 0x57, 0x89, 0xba, 0x75,
	0xee, 0x40, 0x49, 0x00, 0xde, 0xca, 0x7a, 0xe1, 0x33, 0x6f, 0x65, 0x54, 0x6e, 0x67, 0xf3, 0x99,
	0x97, 0x1b, 0xb5, 0xb4, 0x0d, 0xfb, 0xcc, 0x5b, 0x1a, 0x35, 0xb5, 0x5b, 0xf4, 0x99, 0x37, 0x25,
	0x21, 0xdc, 0xd1, 0xb8, 0xd2, 0x73, 0x85, 0x76, 0x4b, 0x6d, 0x56, 0x4a, 0xda, 0x03, 0xa8, 0x8c,
	0xd8, 0xb5, 0x12, 0xfa, 0x1c, 0x4e, 0x1c, 0xf9, 0x2e, 0x51, 0x18, 0xc5, 0xf9, 0x15, 0xaa, 0x9d,
	0x3b, 0xa4, 0xcf, 0x20, 0xa8, 0xbf, 0x3a, 0xc3, 0xce, 0x33, 0x54, 0x22, 0x9a, 0xa1, 0x65, 0xdb,
	0x6c, 0xad, 0xe9, 0x13, 0x68, 0xaf, 0x6d, 0xdd, 0x59, 0xf4, 0x27, 0xb4, 0xcc, 0xd3, 0x23, 0xc7,
	0xb0, 0x3f, 0x96, 0x89, 0xbd, 0x3e, 0x62, 0xe6, 0x68, 0x22, 0x4a, 0x2e, 0xad, 0x3b, 0x47, 0xcc,
	0x1c, 0x4d, 0x44, 0xe3, 0xca, 0x3a, 0xd4, 0x66, 0xe6, 0x48, 0xee, 0x83, 0xff, 0x23, 0xe1, 0xe9,
	0x95, 0xf5, 0xe9, 0x90, 0x39, 0x51, 0x46, 0x87, 0xd6, 0xaf, 0x22, 0x3a, 0x74, 0xf5, 0xb4, 0xf5,
	0xcb, 0x37, 0xf5, 0x34, 0xbd, 0x84, 0x96, 0x79, 0xce, 0x86, 0xd7, 0x5c, 0x27, 0xe5, 0x14, 0x4e,
	0x90, 0x9e, 0x89, 0x26, 0x98, 0x85, 0x7b, 0xf6, 0xc3, 0xd1, 0xf4, 0xdf, 0x71, 0x00, 0xfd, 0xed,
	0x01, 0xb9, 0x90, 0x42, 0xe0, 0x58, 0x73, 0x29, 0xd6, 0x6f, 0xf6, 0x11, 0x1c, 0xb9, 0x2f, 0xd9,
	0x10, 0x55, 0xc6, 0xa5, 0x28, 0xca, 0x6f, 0x06, 0xc9, 0x00, 0x4e, 0xd2, 0xdb, 0x6b, 0x08, 0x7d,
	0xfb, 0x93, 0x67, 0x4d, 0xef, 0xb4, 0x86, 0xb1, 0xed, 0x4c, 0x1a, 0x00, 0x7c, 0x96, 0x65, 0x0b,
	0xdf, 0x0f, 0x6c, 0xe6, 0xcb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x8c, 0xd6, 0xc4, 0x53,
	0x05, 0x00, 0x00,
}
