// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_interface.proto

package greyvarproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("server_interface.proto", fileDescriptor_2ad2c4f41754552d) }

var fileDescriptor_2ad2c4f41754552d = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x8a, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4b, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x49, 0x2f, 0x4a, 0xad, 0x2c, 0x4b, 0x2c, 0x02, 0xf3, 0xa4, 0xe4, 0x93,
	0x73, 0x32, 0x53, 0xf3, 0x4a, 0xe2, 0x4b, 0xf2, 0xe3, 0xa1, 0xea, 0x73, 0x53, 0x8b, 0x8b, 0x13,
	0xd3, 0x53, 0x8b, 0xf5, 0xa0, 0x0a, 0xa0, 0xc2, 0x25, 0xf9, 0xf1, 0x50, 0xa5, 0xa8, 0x0a, 0x8c,
	0x9e, 0x31, 0x72, 0xf1, 0x07, 0x83, 0xd5, 0x78, 0xc2, 0x6c, 0x12, 0xf2, 0xe3, 0x62, 0x77, 0xce,
	0xcf, 0xcb, 0x4b, 0x4d, 0x2e, 0x11, 0x92, 0xd7, 0x43, 0xb6, 0x4f, 0x0f, 0x2a, 0x9c, 0x99, 0x9f,
	0x17, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xa5, 0x80, 0x5b, 0x41, 0x71, 0x41, 0x7e, 0x5e,
	0x71, 0xaa, 0x12, 0x83, 0x90, 0x13, 0x17, 0x77, 0x40, 0x4e, 0x62, 0x65, 0x6a, 0x51, 0x70, 0x6a,
	0x49, 0x69, 0x81, 0x90, 0x38, 0xaa, 0x16, 0xbf, 0xd4, 0x72, 0x88, 0xac, 0x94, 0x04, 0x9a, 0x44,
	0x3e, 0x92, 0x19, 0xf6, 0x5c, 0x2c, 0xbe, 0xf9, 0x65, 0xa9, 0x42, 0x92, 0xa8, 0x6a, 0x40, 0x62,
	0x30, 0xa7, 0x48, 0x61, 0x93, 0x82, 0x19, 0x90, 0xc4, 0x06, 0x16, 0x35, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xef, 0x58, 0x65, 0x1c, 0x59, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerInterfaceClient is the client API for ServerInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerInterfaceClient interface {
	Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error)
	PlayerSetup(ctx context.Context, in *NewPlayer, opts ...grpc.CallOption) (*NoResponse, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
}

type serverInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewServerInterfaceClient(cc *grpc.ClientConn) ServerInterfaceClient {
	return &serverInterfaceClient{cc}
}

func (c *serverInterfaceClient) Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error) {
	out := new(ConnectionResponse)
	err := c.cc.Invoke(ctx, "/greyvarproto.ServerInterface/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverInterfaceClient) PlayerSetup(ctx context.Context, in *NewPlayer, opts ...grpc.CallOption) (*NoResponse, error) {
	out := new(NoResponse)
	err := c.cc.Invoke(ctx, "/greyvarproto.ServerInterface/PlayerSetup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverInterfaceClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/greyvarproto.ServerInterface/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerInterfaceServer is the server API for ServerInterface service.
type ServerInterfaceServer interface {
	Connect(context.Context, *ConnectionRequest) (*ConnectionResponse, error)
	PlayerSetup(context.Context, *NewPlayer) (*NoResponse, error)
	Move(context.Context, *MoveRequest) (*MoveResponse, error)
}

func RegisterServerInterfaceServer(s *grpc.Server, srv ServerInterfaceServer) {
	s.RegisterService(&_ServerInterface_serviceDesc, srv)
}

func _ServerInterface_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerInterfaceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greyvarproto.ServerInterface/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerInterfaceServer).Connect(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerInterface_PlayerSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewPlayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerInterfaceServer).PlayerSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greyvarproto.ServerInterface/PlayerSetup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerInterfaceServer).PlayerSetup(ctx, req.(*NewPlayer))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerInterface_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerInterfaceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greyvarproto.ServerInterface/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerInterfaceServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greyvarproto.ServerInterface",
	HandlerType: (*ServerInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _ServerInterface_Connect_Handler,
		},
		{
			MethodName: "PlayerSetup",
			Handler:    _ServerInterface_PlayerSetup_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _ServerInterface_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_interface.proto",
}
