name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: bufbuild/buf-action@v1
      with:
        setup_only: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: protoc
      run: make protoc
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Build
      run: make
